defmodule NoteApp.Repo.Migrations.AddNoteTakers do
  @moduledoc """
  This file could be autogenerated with `mix ash_postgres.generate_migrations --name add_note_takers`
  """

  use Ecto.Migration

  def up do
    create table(:note_takers, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :name, :text
    end
  end

  def down do
    drop table(:note_takers)
  end
end
