defmodule NoteApp.Repo.Migrations.AddNotes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations --name add_notes`
  """

  use Ecto.Migration

  def up do
    create table(:notes, primary_key: false) do
      add(:id, :uuid, null: false, primary_key: true)
      add(:title, :text, null: false)
      add(:content, :text, null: false)

      add(
        :note_taker_id,
        references(:note_takers,
          column: :id,
          name: "notes_note_taker_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(table(:notes))
  end
end
