defmodule NoteApp.Repo.Migrations.ModifyNotes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations --name modify_notes`
  """

  use Ecto.Migration

  def up do
    alter table(:notes) do
      add :html, :text
    end
  end

  def down do
    alter table(:notes) do
      remove :html
    end
  end
end
